### Require REST Client VSCode Extenction to run
### https://marketplace.visualstudio.com/items?itemName=humao.rest-client


### Search Query
@query = node

### Search Course
GET http://localhost:5000/search/{{query}} HTTP/1.1 

################

### Course Url
@courseURL = beginner-full-stack-web-development-html-css-react-node-2

### Get Course
GET http://localhost:5000/course/{{courseURL}} HTTP/1.1

################

### Register
POST http://localhost:5000/auth/register HTTP/1.1
Content-Type: application/json

{
    "username":"bruh",
    "email":"bashvtini@gmail.com",
    "password":"123456789"
}

### Login
POST http://localhost:5000/auth/login HTTP/1.1
Content-Type: application/json

{
    "email":"admin@admin.com",
    "password":"123456789"
}

### Forgot Password
POST http://localhost:5000/auth/forgotpassword HTTP/1.1
Content-Type: application/json

{
    "email": "bashvtini@gmail.com"
}


### Check Reset Password token
GET http://localhost:5000/auth/checkresettoken/7f907890f2d7c7e3ae54de76b8725cc0a818d669 HTTP/1.1

### Reset Password

POST http://localhost:5000/auth/resetpassword/7f907890f2d7c7e3ae54de76b8725cc0a818d669 HTTP/1.1
Content-Type: application/json

{
    "password":"bruhmoment"
}

################

### token
@token = hello

### Get User saved courses
GET http://localhost:5000/user/courses HTTP/1.1
Authorization: Bearer {{token}}

### Save Course
POST http://localhost:5000/user/courses HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "cover":"test.jpg",
    "title":"Course 1",
    "source":"Udemy",
    "link":"Url",
    "status":"watching"
}

### Course id
@courseId = 5e9ebc33d2f4e51d2e4b5ac6

### Remove Course
DELETE http://localhost:5000/user/courses/{{courseId}} HTTP/1.1
Authorization:Bearer {{token}}

